/*
 * This file was automatically generated by EvoSuite
 * Mon May 08 20:31:46 CDT 2023
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import org.example.TestGenerationTarget;

public class TestGenerationTargetTest {

  @Test
  public void test00()  throws Throwable  {
      int int0 = 0;
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[1];
      intArray0[0] = int0;
      TestGenerationTarget.findMax(intArray0);
      int int1 = 0;
      TestGenerationTarget.isPrime(int1);
  }

  @Test
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[8];
      int int0 = 0;
      intArray0[0] = int0;
      int int1 = 1;
      intArray0[1] = int1;
      int int2 = (-399);
      intArray0[2] = int2;
      int int3 = (-474);
      intArray0[3] = int3;
      int int4 = 0;
      intArray0[4] = int4;
      int int5 = 1975;
      intArray0[5] = int5;
      int int6 = (-172);
      intArray0[6] = int6;
      int int7 = (-1);
      intArray0[7] = int7;
      TestGenerationTarget.findMax(intArray0);
  }

  @Test
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[8];
      int int0 = 0;
      intArray0[0] = int0;
      int int1 = 1;
      intArray0[1] = int1;
      int int2 = (-399);
      intArray0[2] = int1;
      int int3 = (-474);
      intArray0[3] = int3;
      int int4 = 0;
      intArray0[4] = int4;
      int int5 = 1975;
      intArray0[5] = int5;
      int int6 = (-172);
      intArray0[6] = int6;
      int int7 = (-1);
      TestGenerationTarget.findMax(intArray0);
      int int8 = (-172);
      TestGenerationTarget.isPrime(int8);
  }

  @Test
  public void test03()  throws Throwable  {
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[9];
      int int0 = 5;
      intArray0[0] = int0;
      int int1 = (-2744);
      intArray0[1] = int1;
      int int2 = 2;
      intArray0[2] = int2;
      int int3 = (-3775);
      intArray0[3] = int3;
      int int4 = 1209;
      intArray0[4] = int4;
      int int5 = 465;
      intArray0[5] = int5;
      int int6 = (-1);
      intArray0[6] = int6;
      int int7 = 1;
      intArray0[7] = int7;
      int int8 = 8;
      intArray0[8] = int8;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[4];
      int int9 = (-1784);
      intArray1[0] = int9;
      int int10 = 6;
      intArray1[1] = int10;
      int int11 = 2499;
      intArray1[2] = int11;
      int int12 = 8;
      intArray1[3] = int12;
      TestGenerationTarget.findMax(intArray1);
      int[] intArray2 = null;
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
      }
  }

  @Test
  public void test04()  throws Throwable  {
      int int0 = 2;
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[7];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      int int1 = (-2);
      intArray0[3] = int1;
      intArray0[4] = int0;
      intArray0[5] = int0;
      intArray0[6] = int0;
      int int2 = TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int3 = (-1);
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.findMax(intArray0);
      int int4 = TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(intArray0[0]);
      int int5 = (-474);
      TestGenerationTarget.isPrime(int5);
      String string0 = "';</aMKNe^z(Pe&m";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPrime(int1);
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string0);
      int int6 = 7;
      TestGenerationTarget.isPrime(int6);
      int[] intArray1 = new int[9];
      intArray1[0] = int0;
      intArray1[1] = int1;
      intArray1[2] = int4;
      int int7 = (-1920);
      intArray1[3] = int7;
      intArray1[4] = int2;
      intArray1[5] = int0;
      intArray1[6] = int2;
      int int8 = (-5741);
      intArray1[7] = int8;
      intArray1[8] = int4;
      TestGenerationTarget.findMax(intArray1);
  }

  @Test
  public void test05()  throws Throwable  {
      String string0 = "f#`)jR8H4&u+(#/Tiq";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = new int[3];
      int int0 = 793276299;
      intArray0[0] = int0;
      int int1 = (-1);
      intArray0[1] = int1;
      int int2 = 3;
      intArray0[2] = int2;
      TestGenerationTarget.findMax(intArray0);
  }

  @Test
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[2];
      int int0 = 102;
      intArray0[0] = int0;
      int int1 = (-1784);
      intArray0[1] = int1;
      int int2 = TestGenerationTarget.findMax(intArray0);
      int int3 = TestGenerationTarget.findMax(intArray0);
      String string0 = "U1uUO|ZcNk_mkx";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.findMax(intArray0);
      int int4 = 1778;
      TestGenerationTarget.isPrime(int4);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.isPrime(int2);
      int[] intArray1 = new int[1];
      intArray1[0] = int4;
      TestGenerationTarget.findMax(intArray1);
      String string2 = "";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.isPrime(intArray0[1]);
  }

  @Test
  public void test07()  throws Throwable  {
      int int0 = (-661);
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.isPrime(int0);
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = new int[2];
      intArray0[0] = int0;
      intArray0[1] = int0;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.findMax(intArray0);
      String string2 = "X[#pVlj";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.isPalindrome(string2);
      int int1 = 2543;
      TestGenerationTarget.isPrime(int1);
  }

  @Test
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[6];
      int int0 = 0;
      intArray0[0] = int0;
      int int1 = 1415;
      intArray0[1] = int1;
      int int2 = (-2071942946);
      intArray0[2] = int2;
      int int3 = 13;
      intArray0[3] = int3;
      int int4 = 340;
      intArray0[4] = int4;
      int int5 = 0;
      intArray0[5] = int5;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int6 = (-648);
      TestGenerationTarget.isPrime(int6);
      String string0 = null;
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int7 = 1423;
      TestGenerationTarget.isPrime(int7);
  }

  @Test
  public void test09()  throws Throwable  {
      String string0 = null;
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "b'U$";
      TestGenerationTarget.isPalindrome(string1);
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
      }
  }

  @Test
  public void test10()  throws Throwable  {
      String string0 = "RTS?Qj!x|FPYLG{HJ";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = new int[8];
      int int0 = 0;
      intArray0[0] = int0;
      int int1 = 2;
      intArray0[1] = int1;
      int int2 = (-1784);
      intArray0[2] = int2;
      int int3 = 1;
      intArray0[3] = int3;
      int int4 = 2;
      intArray0[4] = int4;
      int int5 = (-2087);
      intArray0[5] = int5;
      int int6 = 1;
      intArray0[6] = int6;
      int int7 = (-1892685218);
      intArray0[7] = int7;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[5];
      intArray1[0] = int4;
      intArray1[1] = int1;
      intArray1[2] = int0;
      intArray1[3] = int5;
      intArray1[4] = int3;
      TestGenerationTarget.findMax(intArray1);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPalindrome(string0);
      int int8 = (-1974691981);
      TestGenerationTarget.isPrime(int8);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
  }

  @Test
  public void test11()  throws Throwable  {
      String string0 = "_";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "jJ";
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.isPalindrome(string0);
      String string2 = "PKD9ok!ePY+.l7ASo";
      TestGenerationTarget.isPalindrome(string2);
      int int0 = 3;
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.isPalindrome(string1);
      String string3 = "";
      TestGenerationTarget.isPalindrome(string3);
      int int1 = (-1751865062);
      TestGenerationTarget.isPrime(int1);
      int int2 = 1;
      TestGenerationTarget.isPrime(int2);
      TestGenerationTarget.isPalindrome(string1);
      int[] intArray0 = new int[2];
      intArray0[0] = int0;
      intArray0[1] = int0;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int3 = 35;
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(intArray0[1]);
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.isPalindrome(string0);
      int int4 = (-765);
      TestGenerationTarget.isPrime(int4);
      String string4 = "";
      TestGenerationTarget.isPalindrome(string4);
  }

  @Test
  public void test12()  throws Throwable  {
      int[] intArray0 = new int[4];
      int int0 = (-1892685218);
      intArray0[0] = int0;
      int int1 = (-1208);
      intArray0[1] = int1;
      int int2 = (-1095);
      intArray0[2] = int2;
      int int3 = 35;
      intArray0[3] = int3;
      TestGenerationTarget.findMax(intArray0);
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      int int4 = 9;
      TestGenerationTarget.isPrime(int4);
      int int5 = (-1);
      TestGenerationTarget.isPrime(int5);
  }

  @Test
  public void test13()  throws Throwable  {
      int int0 = (-941);
      TestGenerationTarget.isPrime(int0);
      String string0 = "LWvPyspf3DOF";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = new int[9];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      intArray0[4] = int0;
      intArray0[5] = int0;
      int int1 = 836;
      intArray0[6] = int1;
      intArray0[7] = int0;
      intArray0[8] = int0;
      TestGenerationTarget.findMax(intArray0);
      int int2 = 1513;
      TestGenerationTarget.isPrime(int2);
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray1 = null;
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
      }
  }

  @Test
  public void test14()  throws Throwable  {
      int int0 = 1470;
      TestGenerationTarget.isPrime(int0);
      String string0 = "{<zv+eJG:@.^\"S z";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = new int[4];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      TestGenerationTarget.findMax(intArray0);
  }
}
