/*
 * This file was automatically generated by EvoSuite
 * Mon May 01 04:59:07 GMT 2023
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.example.TestGenerationTarget;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TestGenerationTargetTest {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.example.TestGenerationTarget"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TestGenerationTargetTest.class.getClassLoader() ,
      "org.example.TestGenerationTarget"
    );
  } 

  private static void resetClasses() {
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      int int0 = 1;
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[5];
      int int1 = (-1428803455);
      intArray0[0] = int1;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      intArray0[4] = int0;
      TestGenerationTarget.findMax(intArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = null;
      TestGenerationTarget.isPalindrome(string0);
      int int0 = (-2926);
      TestGenerationTarget.isPrime(int0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      int int1 = 2;
      TestGenerationTarget.isPrime(int1);
      TestGenerationTarget.isPrime(int0);
      String string2 = null;
      TestGenerationTarget.isPalindrome(string2);
      int int2 = (-68);
      TestGenerationTarget.isPrime(int2);
      int[] intArray0 = new int[6];
      intArray0[0] = int1;
      intArray0[1] = int1;
      intArray0[2] = int0;
      intArray0[3] = int2;
      intArray0[4] = int0;
      intArray0[5] = int1;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int3 = 1;
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      TestGenerationTarget.findMax(intArray0);
      int int4 = (-1727268099);
      TestGenerationTarget.isPrime(int4);
      int int5 = (-754);
      TestGenerationTarget.isPrime(int5);
      TestGenerationTarget.isPrime(int5);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[3];
      int int0 = (-862);
      intArray0[0] = int0;
      int int1 = (-608);
      intArray0[1] = int1;
      int int2 = 2;
      intArray0[2] = int2;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[6];
      int int3 = (-935);
      intArray1[0] = int3;
      int int4 = 1;
      intArray1[1] = int4;
      int int5 = 71;
      intArray1[2] = int5;
      int int6 = 3;
      intArray1[3] = int6;
      int int7 = (-35);
      intArray1[4] = int7;
      int int8 = 2028;
      intArray1[5] = int8;
      TestGenerationTarget.findMax(intArray1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = "U)I";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = new int[7];
      int int0 = 863;
      intArray0[0] = int0;
      int int1 = (-608);
      intArray0[1] = int1;
      int int2 = 2114;
      intArray0[2] = int2;
      int int3 = 2028;
      intArray0[3] = int3;
      int int4 = (-1);
      intArray0[4] = int4;
      int int5 = (-68);
      intArray0[5] = int5;
      int int6 = (-1);
      intArray0[6] = int6;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int2);
      TestGenerationTarget.isPrime(intArray0[4]);
      int int7 = (-2725);
      TestGenerationTarget.isPrime(int7);
      String string1 = "jKKN 9o+GCTw,_~[";
      TestGenerationTarget.isPalindrome(string1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[6];
      int int0 = (-968);
      intArray0[0] = int0;
      int int1 = (-1521);
      intArray0[1] = int1;
      int int2 = 743;
      intArray0[2] = int2;
      int int3 = (-777);
      intArray0[3] = int3;
      int int4 = (-52);
      intArray0[4] = int4;
      int int5 = (-669);
      intArray0[5] = int5;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = null;
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
         verifyException("org.example.TestGenerationTarget", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[3];
      int int0 = (-1300900675);
      intArray0[0] = int0;
      int int1 = 83;
      intArray0[1] = int1;
      int int2 = (-2083449711);
      intArray0[2] = int2;
      TestGenerationTarget.findMax(intArray0);
      String string0 = "XfF*Uew}";
      TestGenerationTarget.isPalindrome(string0);
      int int3 = (-2056243655);
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[0];
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
         verifyException("org.example.TestGenerationTarget", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = "Array cannot be null or empty";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      int int0 = 4;
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.isPrime(int0);
      int int1 = 1409;
      TestGenerationTarget.isPrime(int1);
      int[] intArray0 = new int[2];
      intArray0[0] = int1;
      intArray0[1] = int1;
      TestGenerationTarget.findMax(intArray0);
      String string2 = "j";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      String string3 = "";
      TestGenerationTarget.isPalindrome(string3);
      int int2 = (-2633);
      TestGenerationTarget.isPrime(int2);
      String string4 = "";
      TestGenerationTarget.isPalindrome(string4);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = " =D1NUlW3|18#\"mJe";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[5];
      int int0 = 0;
      intArray0[0] = int0;
      int int1 = (-1999754712);
      intArray0[1] = int1;
      int int2 = (-2081481655);
      intArray0[2] = int2;
      int int3 = 0;
      intArray0[3] = int3;
      int int4 = (-2085303797);
      intArray0[4] = int4;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[1];
      int int5 = 141;
      intArray1[0] = int5;
      TestGenerationTarget.findMax(intArray1);
      int int6 = 23;
      TestGenerationTarget.isPrime(int6);
      TestGenerationTarget.findMax(intArray1);
      int int7 = (-749972580);
      TestGenerationTarget.isPrime(int7);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = (-2009263129);
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[5];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      intArray0[4] = int0;
      int int1 = TestGenerationTarget.findMax(intArray0);
      int int2 = TestGenerationTarget.findMax(intArray0);
      String string0 = null;
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[7];
      intArray1[0] = int2;
      intArray1[1] = int0;
      intArray1[2] = int0;
      intArray1[3] = int1;
      intArray1[4] = int0;
      intArray1[5] = int2;
      intArray1[6] = int0;
      TestGenerationTarget.findMax(intArray1);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(intArray0[0]);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.findMax(intArray0);
      String string2 = "V@ei '#A%";
      TestGenerationTarget.isPalindrome(string2);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "sOzpQ{Jc)v'hfMzm";
      TestGenerationTarget.isPalindrome(string1);
      int int0 = 1;
      TestGenerationTarget.isPrime(int0);
      int int1 = (-1004);
      TestGenerationTarget.isPrime(int1);
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
         verifyException("org.example.TestGenerationTarget", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[2];
      int int0 = (-5824);
      intArray0[0] = int0;
      int int1 = (-523);
      intArray0[1] = int1;
      int int2 = TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int2);
      String string0 = "j4e";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      String string2 = "";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      String string3 = null;
      TestGenerationTarget.isPalindrome(string3);
      int int3 = TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.findMax(intArray0);
      int int4 = 743;
      TestGenerationTarget.isPrime(int4);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int5 = 1472;
      TestGenerationTarget.isPrime(int5);
      int int6 = (-1759616593);
      TestGenerationTarget.isPrime(int6);
      TestGenerationTarget.findMax(intArray0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int int0 = (-4340);
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[9];
      intArray0[0] = int0;
      int int1 = 4466;
      intArray0[1] = int1;
      intArray0[2] = int0;
      intArray0[3] = int0;
      intArray0[4] = int0;
      intArray0[5] = int0;
      intArray0[6] = int0;
      intArray0[7] = int0;
      intArray0[8] = int0;
      int int2 = TestGenerationTarget.findMax(intArray0);
      String string0 = "M>N";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPrime(int2);
      int int3 = (-206);
      TestGenerationTarget.isPrime(int3);
      int int4 = 1;
      TestGenerationTarget.isPrime(int4);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[5];
      intArray1[0] = int4;
      intArray1[1] = int1;
      int int5 = 9;
      intArray1[2] = int5;
      intArray1[3] = int2;
      intArray1[4] = int4;
      TestGenerationTarget.findMax(intArray1);
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "d";
      TestGenerationTarget.isPalindrome(string1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = 83;
      TestGenerationTarget.isPrime(int0);
      int int1 = (-935);
      TestGenerationTarget.isPrime(int1);
      int[] intArray0 = new int[6];
      intArray0[0] = int1;
      intArray0[1] = int0;
      intArray0[2] = int1;
      intArray0[3] = int0;
      intArray0[4] = int1;
      int int2 = (-968);
      intArray0[5] = int2;
      TestGenerationTarget.findMax(intArray0);
      String string0 = "-a63o{p>j(U)I*JG-";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPrime(intArray0[0]);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      int int3 = 986;
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      int int4 = 715;
      TestGenerationTarget.isPrime(intArray0[5]);
      int int5 = 5;
      TestGenerationTarget.isPrime(int5);
      TestGenerationTarget.isPrime(intArray0[2]);
      String string1 = null;
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.isPrime(intArray0[2]);
      int int6 = (-2076);
      TestGenerationTarget.isPrime(int6);
      TestGenerationTarget.isPrime(intArray0[5]);
      String string2 = "Array cannot be null or empty";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int7 = 1472;
      TestGenerationTarget.isPrime(int7);
      TestGenerationTarget.findMax(intArray0);
  }
}
