/*
 * This file was automatically generated by EvoSuite
 * Mon May 01 04:58:36 GMT 2023
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.example.TestGenerationTarget;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TestGenerationTargetTest {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.example.TestGenerationTarget"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TestGenerationTargetTest.class.getClassLoader() ,
      "org.example.TestGenerationTarget"
    );
  } 

  private static void resetClasses() {
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = "[mJ@U$SzQk";
      TestGenerationTarget.isPalindrome(string0);
      int int0 = (-2073);
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[7];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      int int1 = 2;
      intArray0[4] = int1;
      intArray0[5] = int0;
      intArray0[6] = int0;
      TestGenerationTarget.findMax(intArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPalindrome(string0);
      int int0 = (-1);
      TestGenerationTarget.isPrime(int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = "S4'8d$\"1yKXW  )qm";
      TestGenerationTarget.isPalindrome(string0);
      int int0 = 2;
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[9];
      int int1 = 4776;
      intArray0[0] = int1;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      intArray0[4] = int0;
      intArray0[5] = int0;
      intArray0[6] = int0;
      intArray0[7] = int0;
      intArray0[8] = int0;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[7];
      int int0 = (-1881);
      intArray0[0] = int0;
      int int1 = (-1419);
      intArray0[1] = int1;
      int int2 = 60;
      intArray0[2] = int2;
      int int3 = (-1);
      intArray0[3] = int3;
      int int4 = (-312);
      intArray0[4] = int4;
      int int5 = (-2163);
      intArray0[5] = int5;
      int int6 = (-1);
      intArray0[6] = int6;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = null;
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
         verifyException("org.example.TestGenerationTarget", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = "u";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[9];
      int int0 = (-2352);
      intArray0[0] = int0;
      int int1 = 0;
      intArray0[1] = int1;
      int int2 = 2;
      intArray0[2] = int2;
      int int3 = 1;
      intArray0[3] = int3;
      int int4 = 719;
      intArray0[4] = int4;
      int int5 = (-2070);
      intArray0[5] = int5;
      int int6 = 0;
      intArray0[6] = int6;
      int int7 = 651;
      intArray0[7] = int7;
      int int8 = (-1);
      intArray0[8] = int8;
      TestGenerationTarget.findMax(intArray0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      int int9 = 260;
      TestGenerationTarget.isPrime(int9);
      String string2 = "";
      TestGenerationTarget.isPalindrome(string2);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = (-5824);
      TestGenerationTarget.isPrime(int0);
      String string0 = "vkj4e?na&a0(cDx&#_.";
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
         verifyException("org.example.TestGenerationTarget", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[9];
      int int0 = 3664;
      intArray0[0] = int0;
      int int1 = (-3546);
      intArray0[1] = int1;
      int int2 = (-109);
      intArray0[2] = int2;
      int int3 = (-2201);
      intArray0[3] = int3;
      int int4 = 1123;
      intArray0[4] = int4;
      int int5 = 719;
      intArray0[5] = int5;
      int int6 = 0;
      intArray0[6] = int6;
      int int7 = 2;
      intArray0[7] = int7;
      int int8 = (-1);
      intArray0[8] = int8;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray1 = new int[7];
      int int9 = 2708;
      intArray1[0] = int9;
      int int10 = 16;
      intArray1[1] = int10;
      int int11 = (-2205);
      intArray1[2] = int11;
      int int12 = (-312);
      intArray1[3] = int12;
      int int13 = 2462;
      intArray1[4] = int13;
      int int14 = 561745618;
      intArray1[5] = int14;
      int int15 = 561745618;
      intArray1[6] = int15;
      TestGenerationTarget.findMax(intArray1);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray1);
      String string1 = ";ge'!;md&u]=B =D1NU";
      TestGenerationTarget.isPalindrome(string1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = 0;
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[8];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      int int1 = 0;
      intArray0[3] = int1;
      intArray0[4] = int0;
      intArray0[5] = int0;
      intArray0[6] = int0;
      intArray0[7] = int0;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[2];
      intArray1[0] = int0;
      intArray1[1] = int0;
      TestGenerationTarget.findMax(intArray1);
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.isPrime(int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = (-883);
      TestGenerationTarget.isPrime(int0);
      int[] intArray0 = new int[5];
      intArray0[0] = int0;
      intArray0[1] = int0;
      intArray0[2] = int0;
      intArray0[3] = int0;
      intArray0[4] = int0;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      String string0 = "";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int1 = (-1747);
      TestGenerationTarget.isPrime(int1);
      TestGenerationTarget.findMax(intArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[] intArray0 = new int[2];
      int int0 = (-2993);
      intArray0[0] = int0;
      int int1 = 118;
      intArray0[1] = int1;
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[4];
      intArray1[0] = int1;
      intArray1[1] = int0;
      int int2 = (-387);
      intArray1[2] = int2;
      intArray1[3] = int1;
      TestGenerationTarget.findMax(intArray1);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int[] intArray2 = new int[1];
      intArray2[0] = int1;
      TestGenerationTarget.findMax(intArray2);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      String string0 = "A%86&O";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(intArray0[1]);
      TestGenerationTarget.isPrime(intArray0[0]);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray2);
      int int3 = 6;
      TestGenerationTarget.isPrime(int3);
      String string1 = "+y_kLw";
      TestGenerationTarget.isPalindrome(string1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TestGenerationTarget testGenerationTarget0 = new TestGenerationTarget();
      int[] intArray0 = new int[9];
      int int0 = (-1175);
      intArray0[0] = int0;
      int int1 = (-498);
      intArray0[1] = int1;
      int int2 = 0;
      intArray0[2] = int2;
      int int3 = (-1959);
      intArray0[3] = int3;
      int int4 = (-1882);
      intArray0[4] = int4;
      int int5 = (-1);
      intArray0[5] = int5;
      int int6 = 3475;
      intArray0[6] = int6;
      int int7 = 2;
      intArray0[7] = int7;
      int int8 = (-1006);
      intArray0[8] = int8;
      TestGenerationTarget.findMax(intArray0);
      int[] intArray1 = new int[2];
      int int9 = (-1899);
      intArray1[0] = int9;
      int int10 = (-487);
      intArray1[1] = int10;
      TestGenerationTarget.findMax(intArray1);
      int[] intArray2 = new int[8];
      int int11 = 2708;
      intArray2[0] = int11;
      int int12 = (-3175);
      intArray2[1] = int12;
      int int13 = 793276299;
      intArray2[2] = int13;
      int int14 = (-689);
      intArray2[3] = int14;
      int int15 = (-2271);
      intArray2[4] = int15;
      int int16 = 94;
      intArray2[5] = int16;
      int int17 = (-1);
      intArray2[6] = int17;
      int int18 = 16;
      intArray2[7] = int18;
      TestGenerationTarget.findMax(intArray2);
      int int19 = 43;
      TestGenerationTarget.isPrime(int19);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        TestGenerationTarget.findMax(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Array cannot be null or empty
         //
         verifyException("org.example.TestGenerationTarget", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = 940;
      TestGenerationTarget.isPrime(int0);
      int int1 = 1;
      TestGenerationTarget.isPrime(int1);
      int[] intArray0 = new int[1];
      intArray0[0] = int0;
      int int2 = TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int2);
      String string0 = "Y7![fPfz[";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[] intArray0 = new int[2];
      int int0 = (-5824);
      intArray0[0] = int0;
      int int1 = (-523);
      intArray0[1] = int1;
      int int2 = TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPrime(int2);
      String string0 = "j4e";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      String string2 = "";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      String string3 = null;
      TestGenerationTarget.isPalindrome(string3);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      int int3 = 743;
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int4 = 1472;
      TestGenerationTarget.isPrime(int4);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.isPalindrome(string2);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int int0 = 1;
      TestGenerationTarget.isPrime(int0);
      int int1 = (-935);
      TestGenerationTarget.isPrime(int1);
      int[] intArray0 = new int[6];
      intArray0[0] = int1;
      intArray0[1] = int0;
      intArray0[2] = int1;
      intArray0[3] = int0;
      intArray0[4] = int1;
      int int2 = (-1428803455);
      intArray0[5] = int2;
      TestGenerationTarget.findMax(intArray0);
      String string0 = "-a63o{p>j(U)I*JG-";
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.isPalindrome(string0);
      int[] intArray1 = new int[6];
      TestGenerationTarget.findMax(intArray1);
      int int3 = 986;
      TestGenerationTarget.isPrime(int3);
      TestGenerationTarget.isPalindrome(string0);
      int int4 = 715;
      TestGenerationTarget.isPrime(int4);
      int int5 = 5;
      TestGenerationTarget.isPrime(int5);
      TestGenerationTarget.isPalindrome(string0);
      String string1 = null;
      TestGenerationTarget.isPalindrome(string1);
      TestGenerationTarget.isPrime(intArray0[2]);
      int int6 = (-2076);
      TestGenerationTarget.isPrime(int6);
      TestGenerationTarget.isPrime(intArray0[5]);
      String string2 = "Array cannot be null or empty";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.findMax(intArray0);
      TestGenerationTarget.findMax(intArray0);
      int int7 = 1472;
      TestGenerationTarget.isPrime(int7);
      TestGenerationTarget.isPalindrome(string1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = "Array cannot be null or empty";
      TestGenerationTarget.isPalindrome(string0);
      String string1 = "";
      TestGenerationTarget.isPalindrome(string1);
      int int0 = 4;
      TestGenerationTarget.isPrime(int0);
      TestGenerationTarget.isPrime(int0);
      int int1 = 1409;
      TestGenerationTarget.isPrime(int1);
      int[] intArray0 = new int[2];
      intArray0[0] = int1;
      intArray0[1] = int1;
      TestGenerationTarget.findMax(intArray0);
      String string2 = "j";
      TestGenerationTarget.isPalindrome(string2);
      TestGenerationTarget.isPalindrome(string0);
      TestGenerationTarget.findMax(intArray0);
      String string3 = "";
      TestGenerationTarget.isPalindrome(string3);
      int int2 = (-2633);
      TestGenerationTarget.isPrime(int2);
      String string4 = "";
      TestGenerationTarget.isPalindrome(string4);
  }
}
